version: "3"
services:
  spacemesh-node-01: 
    container_name: spacemesh-node-01
    build: .
    image: spacemesh-node
    ports:
      # expose default metrics port
      - "1010" 
    volumes:
      # the volume for the node state, db, etc.
      - spacemesh-node-01:/container/go-spacemesh/build/volume
      # mount the post data folder into the container
      - C:\Users\menze\post\post_node_1:/container/go-spacemesh/build/post_data
    environment:
      - SMESHING_COINBASE_ADDRESS=sm1qqqqqqrpz2djpyfzqa9dlrxv428fehnr78fusfqc8qr30
      # use parameters from postdata_metadata.json
      - FILE_SIZE=2147483648
      - NUMUNITS=8
      # mainnet config
      - CONFIG=./config.mainnet.json
    restart: unless-stopped
    networks: 
      - spacemesh

  # run more nodes with different config. !! make sure to never run two nodes with the same post folder, you will get banned !!

  # spacemesh-node-02:
  #   container_name: spacemesh-node-02
  #   build: .
  #   image: spacemesh-node
  #   ports:
  #     - "1010" 
  #   volumes:
  #     - spacemesh-node-02:/container/go-spacemesh/build/volume
  #   environment:
  #     # - SMESHING_COINBASE_ADDRESS=sm1qqqqqq...
  #     # - FILE_SIZE=34359738368
  #     # - NUMUNITS=4
  #     # - METRICPORT=1011
  #     - CONFIG=./config.mainnet.json
  #   restart: unless-stopped
  #   networks: 
  #     - spacemesh

      
  # spacemesh-node-03:
  #   <<: *sm_node
  #   container_name: spacemesh-node-03
  #   ports:
  #     - "1010" 
  #   volumes:
  #     - spacemesh-node-03:/container/go-spacemesh/build/volume
  #   environment:
  #     # - SMESHING_COINBASE_ADDRESS=sm1qqqqqq...
  #     # - FILE_SIZE=34359738368
  #     # - NUMUNITS=4
  #     # - METRICPORT=1011
  #     - CONFIG=./config.mainnet.json
  #   restart: unless-stopped
  #   networks: 
  #     - spacemesh


# the internal network for the nodes and grafana and prometheus to talk to each other
networks:
  spacemesh:
    external: true
    name: spacemesh


# node_data volumes, one for each node
volumes:
  spacemesh-node-01:
    external: true
    name: spacemesh-node-01
  spacemesh-node-02:
    external: true
    name: spacemesh-node-02
  spacemesh-node-03:
    external: true
    name: spacemesh-node-03